## Part 1 - Numpy array and basics


In [1]:
import numpy as np

### creating array from list


In [ ]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array", arr_1d)

arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("2D array", arr_2d)

1D array [1 2 3 4 5]
2D array [[1 2 3]
 [4 5 6]]


### List vs numpy array


In [ ]:
py_list = [1, 2, 3]
print("Python list multiplication ", py_list * 2)


np_array = np.array([1, 2, 3])  # element wise multiplication
print("Python array multiplication ", np_array * 2)

import time

start = time.time()
py_list = [i * 2 for i in range(1000000)]
print("\n List operation time: ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time: ", time.time() - start)

Python list multiplication  [1, 2, 3, 1, 2, 3]
Python array multiplication  [2 4 6]

 List operation time:  0.0632474422454834

 Numpy operation time:  0.004975557327270508


Vector, Matrix and Tensor


In [ ]:
vector = np.array([1, 2, 3])
print("Vector: ", vector)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix: ", matrix)

tensor = np.array([[[1, 2], [3, 4]], [[4, 5], [6, 7]]])
print("Tensor: ", tensor)

Vector:  [1 2 3]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[4 5]
  [6 7]]]


### Array Properties

In [11]:
arr = np.array([[1,2,3], [4,5,6]])

print("Array Shape: ", arr.shape)
print("Array Dimension: ", arr.ndim)
print("Array Size: ", arr.size)
print("Array Data type: ", arr.dtype)

Array Shape:  (2, 3)
Array Dimension:  2
Array Size:  6
Array Data type:  int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3,4))
print("\nReshaped array: ", reshaped)

flattened = reshaped.flatten()
print("\n Flattened array ", flattened)

# ravel (returns view, instead of copy)
raveled = reshaped.ravel()
print("\n raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("\n Transposed array ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
