# Numpy Practice

Questions from: https://pynative.com/python-numpy-exercise/

In [2]:
import numpy as np

Exercise 1: Create a 1D NumPy array of numbers from 0 to 9

In [3]:
arr = np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


Exercise 2: Convert 1D array to 2D

In [5]:
reshaped_arr = np.reshape(arr, (2,5))

print("Original Array:", arr)
print("\nReshaped 2x5 Array:", reshaped_arr)

Original Array: [0 1 2 3 4 5 6 7 8 9]

Reshaped 2x5 Array: [[0 1 2 3 4]
 [5 6 7 8 9]]


Exercise 3: Print Array Attributes

In [6]:
my_array = np.array([[1, 2], [3, 4], [5, 6], [7, 8]], dtype=np.uint16)

print("The shape of the array is:", my_array.shape)
print("The number of dimensions is:", my_array.ndim)
print("The size of each element in bytes is:", my_array.itemsize)

The shape of the array is: (4, 2)
The number of dimensions is: 2
The size of each element in bytes is: 2


Exercise 4: Create a 3×3 NumPy array of all True

In [9]:
true_arrs = np.ones(shape=(3,3), dtype=bool)
print(true_arrs)

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


Exercise 5: Extract the documentation of NumPy’s arange() function

In [10]:
print(np.info(np.arange))

arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The inter

Exercise 6: Create a 1D array filled with zeros and another filled with ones

In [12]:
zeros_arr = np.zeros(5)
ones_arr = np.ones(5)

print("Zeros:", zeros_arr)
print("Ones:", ones_arr)

Zeros: [0. 0. 0. 0. 0.]
Ones: [1. 1. 1. 1. 1.]


Exercise 7: Create a 1D array of 10 evenly spaced values between 5 and 50

In [13]:
arr = np.arange(5, 51, 5)
print(arr)

[ 5 10 15 20 25 30 35 40 45 50]


Exercise 8: Convert a Python list into a NumPy array

In [14]:
py_list = [1,2,3,4,5]

numpy_arr = np.array(py_list)

print("Python list: ", py_list)
print("Numpy list: ", numpy_arr)

Python list:  [1, 2, 3, 4, 5]
Numpy list:  [1 2 3 4 5]


Exercise 9: Find the memory size of a NumPy array of numbers from 0 to 9

In [18]:
arr = np.arange(10)

print("Array:", arr)
print("Memory size in bytes:", arr.nbytes)

Array: [0 1 2 3 4 5 6 7 8 9]
Memory size in bytes: 80


Exercise 10: Reverse a 1D NumPy array

In [19]:
print(arr[::-1])

[9 8 7 6 5 4 3 2 1 0]


Exercise 11: Create a 3×3 identity matrix

In [20]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Exercise 12: Create a 4×4 array and extract its first row and last column

In [23]:
arr_4d = np.arange(1,17).reshape((4,4))

print("Array:", arr_4d)
print("First Row:", arr_4d[0])
print("Last Column:", arr_4d[:,-1])

Array: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]
